/**
 * Single source of truth for portfolio work items.
 * Used by the craft page and NeuralPortfolio so the craft page does not load the full NeuralPortfolio module.
 */
export type CardAspectRatio = '4/3' | '1/1' | '3/4' | '16/9';

export interface WorkItem {
  id: string;
  title: string;
  category: 'product' | 'film' | 'interaction' | 'writing';
  thumbnail: string;
  video?: string;
  cardImage?: string;
  videoStart?: number;
  videoLoopSec?: number;
  videoFullLoop?: boolean;
  videoObjectFit?: 'cover' | 'contain';
  videoScale?: number;
  /** Card frame aspect ratio in masonry; defaults to 4/3 when omitted */
  cardAspectRatio?: CardAspectRatio;
  href: string;
  excerpt?: string;
  year?: string;
}

/** Bump `?v=` when replacing `public/videos/promise_website_demo.mp4` so cached responses invalidate. */
export const PROMISE_WEBSITE_DEMO_VIDEO = '/videos/promise_website_demo.mp4?v=2';

export const WORK_ITEMS: WorkItem[] = [
  {
    id: 'payment-status',
    title: 'Payment status',
    category: 'interaction',
    thumbnail: '',
    video: '/videos/payment_processing.mp4',
    cardAspectRatio: '1/1',
    href: '/payment-status',
    excerpt: 'A button that cycles through payment states. Each state gets its own motion.',
    year: 'January 2026',
  },
  {
    id: 'craft',
    title: 'Craft',
    category: 'product',
    thumbnail: '/thumbnails/craft.png',
    video: '/videos/craft_video.mp4',
    videoFullLoop: true,
    cardAspectRatio: '4/3',
    href: '/products/craft',
    excerpt: 'A concept for refining AI-generated components with live controls and immediate visual feedback.',
    year: 'July 2025',
  },
  {
    id: 'promise-website',
    title: 'Promise website',
    category: 'product' as const,
    year: '2025',
    href: '/products/promise-website',
    video: PROMISE_WEBSITE_DEMO_VIDEO,
    thumbnail: '/videos/thumbnails/promise_website_preview.mp4',
    excerpt: 'A coded redesign of Promise\'s marketing site. An unreleased direction.',
  },
  {
    id: 'photoboom',
    title: 'Photo boom',
    category: 'interaction',
    thumbnail: '',
    video: '/videos/photo_boom_video.mp4',
    cardAspectRatio: '3/4',
    href: '/photoboom',
    excerpt: 'A photo stack that explodes from wherever you click.',
    year: 'January 2026',
  },
  {
    id: 'electric-border',
    title: 'Electric border',
    category: 'interaction',
    thumbnail: '',
    video: '/videos/electric_border.mp4',
    cardAspectRatio: '16/9',
    href: '/interactions/electric-border',
    excerpt: 'A card border that writhes. Driven by SVG displacement maps and animated turbulence noise.',
    year: 'January 2026',
  },
  {
    id: 'visual-system-hover',
    title: 'Visual system hover',
    category: 'interaction',
    thumbnail: '',
    video: '/videos/visal_hover.mp4',
    videoFullLoop: true,
    cardAspectRatio: '1/1',
    href: '/visual-system-hover',
    excerpt: 'A bento grid where each card previews a video on hover. Clicking opens a draggable, resizable vintage Mac window.',
    year: 'January 2025',
  },
  {
    id: 'film-02',
    title: 'FedCaddy commercial',
    category: 'film',
    thumbnail: '/thumbnails/film-02.jpg',
    video: '/videos/fedcaddy_video_1%20(1).mp4',
    videoFullLoop: true,
    cardAspectRatio: '4/3',
    href: '/films/film-02',
    excerpt: 'Brief description of the project.',
    year: 'November 2016',
  },
  {
    id: 'bloom',
    title: 'Bloom',
    category: 'interaction',
    thumbnail: '',
    video: '/videos/bloom_video.mp4',
    videoFullLoop: true,
    cardAspectRatio: '16/9',
    href: '/interactions/bloom',
    excerpt: 'iOS-inspired pull-down menu, reverse-engineered and packaged.',
    year: 'January 2026',
  },
  {
    id: 'co-creator',
    title: 'Co-creator',
    category: 'product',
    thumbnail: '/thumbnails/co-creator.jpg',
    video: '/videos/taste_demo.mp4',
    cardAspectRatio: '4/3',
    href: '/products/co-creator',
    excerpt: 'AI co-designer that turns taste into a complete design system.',
    year: 'February 2026',
  },
  {
    id: 'essay-01',
    title: "We've been here before",
    category: 'writing',
    thumbnail: '/thumbnails/essay-01.jpg',
    cardImage: '/images/essays/retro_vintage.png',
    href: '/essays/essay-01',
    excerpt: "Every generation believes it is living through the most consequential technological moment in history. Usually they're right.",
    year: 'December 2024',
  },
  {
    id: 'carousel',
    title: 'Netflix film scroll',
    category: 'interaction',
    thumbnail: '/thumbnails/carousel.jpg',
    video: '/videos/netflix_scroll.mp4',
    href: '/interactions/carousel',
    excerpt: 'A horizontal scroll with hover lift, parallax drift, and mobile focus scaling.',
    year: 'November 2024',
  },
  {
    id: 'keycadets',
    title: 'Keycadets (acquired)',
    category: 'product',
    thumbnail: '/thumbnails/keycadets.png',
    video: '/images/keycadets/248285912_4711445322210021_8637902604872814185_n.MOV',
    href: '/products/keycadets',
    excerpt: 'Founded, designed, and scaled a premium mechanical keyboard brand to national retail. Acquired 2024.',
    year: '2019–2024',
  },
  {
    id: 'film-01',
    title: 'Engineering at Promise',
    category: 'film',
    thumbnail: '/thumbnails/film-01.jpg',
    video: '/videos/promise_commercial_preview.mp4',
    videoFullLoop: true,
    href: '/films/film-01',
    excerpt: 'Brief description of the project.',
    year: 'July 2025',
  },
  {
    id: 'sunset',
    title: 'Sunset chaser',
    category: 'product',
    thumbnail: '/thumbnails/sunset.png',
    video: '/videos/sunset_chaser.mp4',
    videoStart: 1,
    videoFullLoop: true,
    href: '/products/sunset',
    excerpt: 'A location-aware iOS concept that tells you exactly when to step outside.',
    year: 'December 2025',
  },
  {
    id: 'thistrackiscrack',
    title: 'Thistrackiscrack (acquired)',
    category: 'product',
    thumbnail: '/thumbnails/thistrackiscrack.jpg',
    video: '/images/thistrackiscrack/trackiscrack.MOV',
    href: '/products/thistrackiscrack',
    excerpt: 'A music discovery blog I built in high school. It went viral. It was acquired.',
    year: '2008',
  },
  {
    id: 'film-04',
    title: 'Zeke Sanders: Slice of pie',
    category: 'film',
    thumbnail: '/thumbnails/film-04.jpg',
    video: '/videos/slice%20of%20pie.mp4',
    videoFullLoop: true,
    videoObjectFit: 'cover',
    videoScale: 1.15,
    href: '/films/film-04',
    excerpt: 'Brief description of the project.',
    year: 'June 2023',
  },
  {
    id: 'ai-document-verification',
    title: 'Intelligent document review',
    category: 'product',
    thumbnail: '/thumbnails/ai-document-verification.jpg',
    video: '/videos/document_review_preview.mp4',
    videoObjectFit: 'cover',
    videoFullLoop: true,
    cardAspectRatio: '3/4',
    href: '/products/ai-document-verification',
    excerpt: 'AI-powered eligibility verification that keeps humans in the loop.',
    year: 'January 2026',
  },
  {
    id: 'doritos-loaded',
    title: 'Doritos loaded',
    category: 'product',
    thumbnail: '/thumbnails/doritos-loaded.jpg',
    video: '/images/doritos/231215_The-Garage_Doritos_S01_1x1_H264.mp4',
    cardImage: '/images/doritos/DOR001_PBD_Shot_33_V2_4x5.jpg',
    cardAspectRatio: '1/1',
    href: '/products/doritos-loaded',
    excerpt: 'End-to-end brand activation for Doritos at Coachella — digital ordering, physical booth, and event capture.',
    year: 'June 2023',
  },
  {
    id: 'essay-03',
    title: 'Tuesday night heartbreak',
    category: 'writing',
    thumbnail: '',
    cardImage: '/images/essays/tuesday_night.png',
    href: '/essays/essay-03',
    excerpt: "The loneliness isn't from being alone. It's from never letting yourself fully arrive.",
    year: 'January 2026',
  },
  {
    id: 'film-03',
    title: 'M8 commercial',
    category: 'film',
    thumbnail: '/thumbnails/film-03.jpg',
    video: '/videos/m8_video_preview.mp4',
    videoFullLoop: true,
    cardAspectRatio: '3/4',
    href: '/films/film-03',
    excerpt: 'Brief description of the project.',
    year: 'November 2013',
  },
  {
    id: 'essay-02',
    title: "Amara's law",
    category: 'writing',
    thumbnail: '',
    cardImage: "/images/essays/Amara's Law.png",
    href: '/essays/essay-02',
    excerpt: "Amara's Law says we overestimate technology in the short term and underestimate it in the long term. We're in the short term right now.",
    year: 'January 2025',
  },
  {
    id: 'film-05',
    title: 'The Zeke Sanders story',
    category: 'film',
    thumbnail: '/thumbnails/film-05.jpg',
    video: '/videos/zeke%20sanders.mp4',
    videoFullLoop: true,
    videoObjectFit: 'cover',
    videoScale: 1.15,
    href: '/films/film-05',
    excerpt: 'Brief description of the project.',
    year: 'June 2021',
  },
  {
    id: 'ramin-skill',
    title: 'Design engineer skill',
    category: 'interaction',
    thumbnail: '',
    /** Bump `v` when replacing the file so clients don’t keep a cached copy */
    video: '/videos/payment_plan_skill.mp4?v=4',
    cardAspectRatio: '1/1',
    videoObjectFit: 'contain',
    href: '/interactions/ramin-skill',
    excerpt:
      'A CLI skill for design and engineering review—animation, forms, mobile, and hierarchy in one pass.',
    year: 'March 2026',
  },
];
